### PR TITLE
Slim 4

### LINKED ISSUE #22: Slim 4 support
Hello! Thank you for great project, I'm using it extensively and having a lot of fun an delight with all theese autowirings and nice config)

There is work in progress for Slim 4 for more than half a year:

https://github.com/slimphp/Slim/tree/4.x

Slim is going to keep it's honor of most interchangeble framework in PHP universe. PHP-DI\Slim-Bridge should definitely support new version, so I forked this repo and started to hack something together: 

https://github.com/SergeAx/Slim-Bridge/tree/dev-4x

Alas. I stumbled upon nasty error about 'calling non-static method statically':

https://travis-ci.org/SergeAx/Slim-Bridge/jobs/256378905

Maybe someone here more familiar with PHP-DI and Slim-Bridge can easily point out an error?

### PR DESCRIPTION
**Pull request by mnapoli**
Originally #46

resolves #22

TODO:

- [ ] require Slim 4.2
- [ ] use https://github.com/slimphp/Slim/pull/2793 instead

### CODE REVIEW

**Review by fritsvt — APPROVED** [review]

**Comment by l0gicgate** [comment]
Just a heads up @mnapoli there will be upcoming breaking changes to `CallableResolverInterface` in Slim 4.2

I know, there’s already a lot of BC changes but unfortunately we have to do this so `MiddlewareDispatcher` becomes dependant on `CallableResolver` instead of duplicating a bunch of logic to resolve callables. 

See https://github.com/slimphp/Slim/issues/2780 for more information

**Comment by mnapoli** [comment]
I'm putting this on hold waiting for https://github.com/slimphp/Slim/pull/2793

@l0gicgate I'm commenting in the issue you linked to.

**Comment by l0gicgate** [comment]
@mnapoli I think we’re in the clear here. Just released 4.2 today and we avoided all potential BCs thankfully!

**Comment by mnapoli** [comment]
@l0gicgate awesome, thank you for letting me know!

**Comment by xndr78** [comment]
cannot wait for slim 4 support

**Comment by opengeek** [comment]
Is this ready to go? Is there a way to use this via composer so I can try it out on some existing projects I would like to upgrade to Slim 4?

**Comment by alturic** [comment]
Any update on this? Definitely interested in testing this out on Slim 4.

**Comment by mnapoli** [comment]
I have updated the issue description with a TODO list of what's left to do.

I have loads of work this week, I hope to get on this next week.

**Comment by fritsvt** [comment]
Hi @mnapoli Thanks for the update! I've created a new PR that solves the two todo items you mentioned here.

**Comment by mnapoli** [comment]
Merged #49, thanks @fritsvt 

I have opened a PR for the documentation as well: https://github.com/PHP-DI/PHP-DI/pull/682

I'll merge everything, tag, release and deploy the new docs.

Thanks everyone for the help!

**Comment by SvenRtbg** [comment]
I think, with this merged https://github.com/PHP-DI/PHP-DI/issues/680 can be closed, too.

**Comment by mnapoli** [comment]
@SvenRtbg yes thanks!

**Pull request merged**
