### PR TITLE
slim 3.3 released.

### PR DESCRIPTION
**Pull request by irfanevrens**

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you but there is no need to require the new version explicitly. It is compatible with 3.2 so it can be installed using Composer without problems.

**Comment by irfanevrens** [comment]
If I use slim 3.3 it will conflict.

**Comment by mnapoli** [comment]
Have you tried?

**Comment by irfanevrens** [comment]
Yes. Than backed 3.2.

**Comment by mnapoli** [comment]
What error message did you get?

**Pull request closed without merging**
